version: '3'
services:
  general_code:
    # Set CURRENT_ID by running CURRENT_UID=$(id -u):$(id -g) docker-compose up
    user: ${CURRENT_UID}
    build: .
    restart: always
    volumes:
      - /mnt/download:/download
      - /mnt/archive:/archive
    command: ./__main__.py --type general

proxy:
  image: abiosoft/caddy
  restart: always
  ports:
    - '80:80'
  volumes:
    - ./Caddyfile-api:/etc/Caddyfile
