version: "3"
services:
    video_code:
        # Set CURRENT_ID by running CURRENT_UID=$(id -u):$(id -g) docker-compose up
        user: ${CURRENT_UID}
        build: .
        restart: always
        volumes:
            - ./src:/code
        ports:
            - "82:8080"
        command: ./__main__.py --type video
        depends_on:
            - pipeline

    # Comment out this container if on production envrionment
    mongodb:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass
