version: '3'
services:
  codebase:
    # Set CURRENT_ID by running CURRENT_UID=$(id -u):$(id -g) docker-compose up
    user: ${CURRENT_UID}
    build: .
    volumes:
      - ./src:/code
    ports:
      - '127.0.0.1:80:1337'
    command: ./__main__.py
    depends_on:
      - pipeline

  pipeline:
    build: .
    volumes:
      - ./src:/code
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - broker
      - mongodb
      - backend

  # Out comment this container if on production envrionment
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  broker:
    image: rabbitmq
    restart: always

  backend:
    image: redis
    restart: always
