version: "3"
services:
    general_code:
        # Set CURRENT_ID by running CURRENT_UID=$(id -u):$(id -g) docker-compose up
        user: ${CURRENT_UID}
        build: .
        restart: always
        volumes:
            - ./src:/code
        ports:
            - "80:8080"
        command: ./__main__.py --type general

    music_code:
        # Set CURRENT_ID by running CURRENT_UID=$(id -u):$(id -g) docker-compose up
        user: ${CURRENT_UID}
        build: .
        restart: always
        volumes:
            - ./src:/code
        ports:
            - "81:8080"
        command: ./__main__.py --type music

    video_code:
        # Set CURRENT_ID by running CURRENT_UID=$(id -u):$(id -g) docker-compose up
        user: ${CURRENT_UID}
        build: .
        restart: always
        volumes:
            - ./src:/code
        ports:
            - "82:8080"
        command: ./__main__.py --type video

    # Comment out this container if on production environment
    mongodb:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass

    # Comment out this container if on production environment
    sqldb:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: pass
