version: '3'
services:
  music_code:
    # Set CURRENT_ID by running CURRENT_UID=$(id -u):$(id -g) docker-compose up
    user: ${CURRENT_UID}
    build: 
      context: .
      dockerfile: ./docker/audio-analysis/Dockerfile
    restart: always
    volumes:
      - /mnt/download:/download
      - /mnt/archive:/archive
    command: ./__main__.py --type music
    depends_on:
      - pipeline

  pipeline:
    user: ${CURRENT_UID}
    build: 
      context: .
      dockerfile: ./docker/audio-analysis/Dockerfile
    restart: always
    volumes:
      - /mnt/download:/download
      - /mnt/archive:/archive
    command: celery -A tasks worker --loglevel=info --concurrency 16 -Ofair
    depends_on:
      - broker
      - backend

  broker:
    image: rabbitmq
    hostname: broker
    restart: always
    volumes:
      - /docker/persistent/rabbitmq:/var/lib/rabbitmq

  backend:
    image: redis
    restart: always
    volumes:
      - /docker/persistent/redis:/data

  flower:
    user: ${CURRENT_UID}
    build: 
      context: .
      dockerfile: ./docker/audio-analysis/Dockerfile
    restart: always
    command: flower -A tasks --port=5555
    depends_on:
      - pipeline

  proxy:
    build: ./docker/proxy
    restart: always
    volumes:
      - caddy:/data
    ports:
      - '80:80'

volumes:
  caddy:
