version: '3'
services:
  # Comment out this container if on production envrionment
  server:
    user: ${CURRENT_UID}
    build: .
    restart: always
    volumes:
      - ./src:/code
    ports:
      - '80:8080'
    command: echo "Not implemented"
