mongo_host: localhost
mongo_port: 27017
mongo_user: root
mongo_pass: pass
mongo_db: admin

sql_type: postgresql
sql_host: sqldb
sql_user: postgres
sql_pass: pass
sql_db: itumir

rest_api_host_url: 0.0.0.0
rest_api_host_port: 8080
rest_api_debug: true

rest_api_general_url: http://general_code:8080
rest_api_music_url: http://music_code:8080
rest_api_video_url: http://video_code:8080

similarity_matches: 10
similarity_bucket_size: 6000

rmq_host: broker
redis_host: backend
