mongo_host: mongodb
mongo_port: 27017
mongo_user: root
mongo_pass: pass
mongo_db: dr

rest_api_host_url: 0.0.0.0
rest_api_host_port: 8080

rest_api_general_url: general_code
rest_api_music_url: music_code
rest_api_video_url: video_code

similarity_matches: 10
similarity_bucket_size: 6000
