mongo_host: mongodb
mongo_port: 27017
mongo_user: root
mongo_pass: pass
mongo_db: dr

rest_api_url: 0.0.0.0
rest_api_port: 1337

similarity_matches: 10
similarity_bucket_size: 6000

rmq_host: broker
redis_host: backend
