mongo_host: mongodb
mongo_port: 27017
mongo_user: root
mongo_pass: pass
mongo_db: dr

sql_type: mysql
sql_host: sqldb
sql_user: root
sql_pass: pass
sql_db: itumir

rest_api_host_url: 0.0.0.0
rest_api_host_port: 8080
rest_api_debug: true

rest_api_general_url: http://general_code:8080
rest_api_music_url: http://music_code:8080
rest_api_video_url: http://video_code:8080

similarity_matches: 10
similarity_bucket_size: 6000
